<?php
define("BASE","http://localhost:82/tellsafe");
define("SECURE","http://localhost:82/tellsafe");
?>
<META NAME="ROBOTS" CONTENT="INDEX,FOLLOW">
<LINK REL="stylesheet" HREF="tellsafe.css" TYPE="text/css">
<link rel="P3Pv1" href="<?php print BASE ?>/w3c/p3p.xml">
</HEAD>
<BODY>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 STYLE="width:100%; height:100%">
<TR><TD COLSPAN=2 STYLE="padding-top:6px; padding-bottom:6px; padding-left:5px"><A HREF="<?php print BASE ?>/tellsafe.php"><IMG SRC="logo.gif" BORDER=0 ALT=""></A></TD></TR>
<TR><TD COLSPAN=2><IMG SRC="bar.gif" BORDER=0 ALT="" STYLE="width:100%; height:11px"></TD></TR>
<TR STYLE="height:100%">
<TD WIDTH=170 VALIGN=top STYLE="background-color:#006699; padding-top:15px; padding-left:15px; padding-right:10px">
<SPAN CLASS="MenuHeader">SUBSCRIBERS</SPAN><BR>
<A HREF="<?php print BASE ?>/subscribe.php" CLASS="Menu">Subscribe Now</A><BR>
<A HREF="<?php print SECURE ?>/secure/signin.php" CLASS="Menu">Member Signin</A><BR><BR>
<SPAN CLASS="MenuHeader">EMPLOYEES</SPAN><BR>
<A HREF="<?php print BASE ?>/employees.php" CLASS="Menu">Employee Area</A><BR><BR>
<SPAN CLASS="MenuHeader">GUESTS</SPAN><BR>
<A HREF="<?php print BASE ?>/tellsafe.php" CLASS="Menu">Home Page</A><BR>
<A HREF="<?php print BASE ?>/about.php" CLASS="Menu">About Us</A><BR>
<A HREF="<?php print BASE ?>/sox301.php" CLASS="Menu">Sarbanes-Oxley</A><BR>
<A HREF="<?php print BASE ?>/security.php" CLASS="Menu">Security</A><BR>
<A HREF="<?php print BASE ?>/clients.php" CLASS="Menu">Client List</A><BR>
<A HREF="<?php print BASE ?>/contact.php" CLASS="Menu">Contact Us</A><BR>
<A HREF="<?php print BASE ?>/feedback.php" CLASS="Menu">Feedback</A><BR>
<A HREF="<?php print BASE ?>/privacy.php" CLASS="Menu">Privacy Policy</A><BR>
<A HREF="<?php print BASE ?>/resources.php" CLASS="Menu">Resources</A><BR>
</TD><TD VALIGN=top STYLE="background-color:#f5f5f5; padding-top:15px; padding-bottom:25px; padding-left:18px; padding-right:30px">
